from .IDataProvider import IDataProvider
from .SemanticSegmentationDataProvider import SemanticSegmentationDataProvider
from .SemanticSegmentationDataProvider import SemanticSegmentationSingleDataProvider
from .RegressionSegmentationDataProvider import RegressionSegmentationDataProvider
from .RegressionSegmentationDataProvider import RegressionSegmentationSingleDataProvider
